### ISSUE TITLE
Provide Download Files

### ISSUE THREAD

**Issue by titanofold** [joelburget/slimlock#12]
This is pretty slick. I'd like to get it added to the main Portage tree of Gentoo.

Before I can offer it to the masses, though, it'd be really nice to have proper tarballs to download rather than grabbing a tag snapshot.

**Comment by joelburget** [comment]
Is there anything wrong with the tarballs on the [tags page](https://github.com/joelburget/slimlock/tags)?

**Comment by titanofold** [comment]
Yes, tags can be changed, and Github uses an unpredictable name for the tarball and for the top folder. It would be more convenient for the package maintainers to have a predictable tarball name, layout, and something that is more permanent than a tag.

**Comment by joelburget** [comment]
I agree the unpredictable names are annoying. Do you know of a convenient place to host the tarballs?

**Comment by titanofold** [comment]
Yes, you can use Github to host the tarballs. Just upload the tarballs to the [Downloads](https://github.com/joelburget/slimlock/downloads) page.
