### ISSUE TITLE
slimlock make problem

### ISSUE THREAD

**Issue by ElF4rih** [joelburget/slimlock#27]
hi im trying to install slimlock but when I try to run the commands " make " and " sudo make install " its shows me this text. what should i do

g++  -Wall -I. -I/usr/include/freetype2 -I/usr/include/libpng16  -pthread -DPACKAGE=\"slimlock\" -DVERSION=\"0.11\" -DPKGDATADIR=\"/usr/share/slim\" -DSYSCONFDIR=\"/etc\"  -c panel.cpp -o panel.o
panel.cpp: In constructor ‘Panel::Panel(Display*, int, Window, Cfg*, const std::string&)’:
panel.cpp:47:15: error: ordered comparison of pointer with integer zero (‘GC’ {aka ‘_XGC*’} and ‘int’)
   47 |     if (WinGC < 0) {
      |         ~~~~~~^~~
make: *** [Makefile:29: panel.o] Error 1

**Comment by joelburget** [comment]
I no longer maintain this project -- please see the maintained version at https://github.com/dannyn/slimlock
