### ISSUE TITLE
cannot suspend

### ISSUE THREAD

**Issue by joelburget** [joelburget/slimlock#4]
"Did a quick test with the newest version and pm-suspend/s2disk continues not to do anything after slimlock has launched. It happens right on the first try so I don't think the problem was the fact that you didn't unlock it afterwards but rather the lock itself."

"Notice that I still can't hibernate while using slimlock (using i3lock for the time being)"

**Comment by DanielBaulig** [comment]
I'm also having trouble suspending using slimlock. All pm-utils hooks seem to be processed successfully, but the actual suspending to sleep will hang and not finish correctly. I'm happy to provide additional feedback to help fixing this issue.

**Comment by joelburget** [comment]
I'm not really sure what the problem is with suspending since I don't use it myself. Here's what I would try:
1. Disable tty locking by setting `tty_lock 0` in /etc/slimlock.conf
2. Disable dpms by setting `dpms_standby_timeout 0`
3. Slimlock is owned by root, would that cause problems with suspending?

Hopefully this is helpful.

**Comment by DRiKE** [comment]
I'm experiencing the same issue. Tried the three suggestions Joel made but that they did not fix the problem.

Installed from aur (using kernel 3.1.9-1-ARCH):
`aur/slimlock-git 20110611-1`

slimlock -v gives:
`slimlock-0.10.1, © 2010 Joel Burget`

Slimlock is called as can be seen in the pm-utils script on the Arch wiki: https://wiki.archlinux.org/index.php/Pm-utils#Locking_the_screen_saver_on_hibernate_or_suspend

**Comment by joelburget** [comment]
@DRiKE I was having the same problem and setting `tty_lock 0` worked for me. Would you mind confirming it doesn't work for you?

**Comment by DRiKE** [comment]
It works when setting `dpms_standby_timeout`, `dpms_off_timeout` and `tty_lock` all to `0` !

**Comment by joelburget** [comment]
Fixed with version 0.11 - `tty_lock 0` is now the default.
