### ISSUE TITLE
Build fails on Arch Linux due to DSOLinkChange

### ISSUE THREAD

**Issue by DanielBaulig** [joelburget/slimlock#6]
Building on ArchLinux (and possibly other distros) fails due to DSOLinkChange. Please refer to [this mailing list thread](http://mailman.archlinux.org/pipermail/arch-general/2011-December/023222.html)  aswell as [this wiki page](http://fedoraproject.org/wiki/UnderstandingDSOLinkChange) on the fedora wiki.

Fixing the issue is as simple as adding -lXext to LIBS in the makefile.

**Comment by joelburget** [comment]
Thanks for the excellent bug report, should be fixed by edf1a2c.
